sudo: required
language: node_js
node_js:
  - 14

services:
  - docker

cache:
  directories:
    - node_modules

# deploy script
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master